//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Florist
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderproduct
    {
        public int id_orderproduct { get; set; }
        public int id_заказа { get; set; }
        public int id_producta { get; set; }
        public int Количество { get; set; }
    
        public virtual tovary tovary { get; set; }
        public virtual zakazy zakazy { get; set; }
    }
}
