//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Florist
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tovary()
        {
            this.orderproduct = new HashSet<orderproduct>();
        }
    
        public int id_товара { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public int код_единицы_измерения { get; set; }
        public int Стоимость { get; set; }
        public int Размер_максимально_возможной_скидки { get; set; }
        public int Код_производителя { get; set; }
        public int Код_поставщика { get; set; }
        public int Код_категории_товара { get; set; }
        public int Действующая_скидка { get; set; }
        public int Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> enable { get; set; }
    
        public virtual edizm edizm { get; set; }
        public virtual kategoriitov kategoriitov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderproduct> orderproduct { get; set; }
        public virtual postavchiki postavchiki { get; set; }
        public virtual proizv proizv { get; set; }
    }
}
