//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Florist
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_пользователя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string отчество { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Код_роли { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
